config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resource :profile, only: :show
  resources :bookings, only: :show

  resources :flats, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end

  namespace :owner do
    resources :flats, only: %i[new create edit update destroy]
    resources :bookings, only: [] do
      member do
        get :accept
        get :decline
      end
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, class_name: "User"
  belongs_to :flat

  validates :status, inclusion: { in: %w[accepted pending declined] }

  validates :start_date, presence: true, comparison: { greater_than: Date.today }
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_one_attached :photo
  belongs_to :owner, class_name: "User"
  has_many :bookings

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_town_and_name, against: [ :town, :name ], using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :bookings, foreign_key: :renter_id
  has_many :flats, foreign_key: :owner_id
  has_many :reservations, through: :flats, source: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController



  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.renter = current_user # user est associé à la création du booking (renter vient de la db)
    @booking.flat = @flat # de la show du dragon, tu récupere id de la foreign key
    @booking.status = "pending"
    if @booking.end_date && @booking.start_date
    @miliseconds1 = @booking.end_date.strftime('%Q')
    @miliseconds2 = @booking.start_date.strftime('%Q')
    @miliseconds = @miliseconds1.to_i - @miliseconds2.to_i
    @days = @miliseconds / 86400000
    @booking.price = @flat.price_per_day * @days
    end


    if @booking.save
      redirect_to booking_path(@booking), notice: "Your location's request has been confirmed"
    else
      render "flats/show", status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flat = @booking.flat
  end



  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)   # A configurer plutard
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end



end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index

    if params[:query].present?
      sql_query = <<~SQL
      flats.town ILIKE :query
      OR flats.name ILIKE :query
      OR users.first_name ILIKE :query
      OR users.last_name ILIKE :query
    SQL
      @flats = Flat.joins(:owner).where(sql_query, query: "%#{params[:query]}%")
    else
      @flats = Flat.all
    end

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: {flat: flat}),
        image_url: helpers.asset_url("home-1.png")
      }
    end

  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    @flats = Flat.all


    @markers = @flats.geocoded.map do |flat|
      if flat = @flat
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: {flat: flat}),
        image_url: helpers.asset_url("home-1.png")
      }
      end
    end

  end


  def new
    @flat = Flat.new
  end


  private

  def flat_params
    params.require(:flat).permit(:name, :description, :price_per_day, :town, :photo)
  end

end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
end

app/controllers/owner/flats_controller.rb
class Owner::FlatsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @flats = Flat.where(owner: current_user)
    # @flats = @user.
    @bookings = @user.bookings

    @reservations = Booking.includes(:flat).where(flats: { owner: @user })
  end

  private

  def set_user
    @user = current_user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container dragon py-5 d-flex justify-content-center" >
  <div class="card" style="width: 900px;">
    <div class="card-body">
    <h1>Réservation de <%= @booking.flat.name%> <em> en cours</em></h1>

      <div class="row">
        <div class="col 12 m-2">

          <%= cl_image_tag @booking.flat.photo.key, height: 300, width: 400, class: "shadow-lg", crop: :fill %>
        </div>

        <div class="col 12 d-flex align-items-center">
          <div class="flex-grow-1">
            <p>La demande vient dêtre envoyé à <%= @booking.flat.owner.first_name %></p>
            <p>Prix de la réservation : <%= @booking.price %> €</p>
          </div>
      </div>
</div>
    </div>
  </div>
</div>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<h3><%= flat.town %></h3>
<p><%= flat.address %></p>

app/views/flats/index.html.erb
<h1 class="title-index"><strong>Our unique selection of flats</strong></h1>

   <%# <div class="search-wrapper">
    <label for="search">Search Flat</label>
    <input type="search" id="search">
    </div> %>
<%= form_with url: flats_path, method: :get, class: "d-flex me-1" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a flat"
  %>
  <%= submit_tag "Search", class: "btn btn-info" %>
<% end %>


      <div class="flat-cards">
        <% @flats.each do |flat| %>
            <div class="card"> <%= link_to flat do %>
              <%= cl_image_tag flat.photo.key, height: 200, crop: :fill, class:"card-img" %>
              <div class="card-index-body">
                <h3 class="card-index-title"><%= flat.name %></h3>
                <h4 class ="card-town-name"><%= flat.town %></h4>
              </div>
              <div>
                <h3 class="card-text-end"> <strong>€ <%= flat.price_per_day %></strong></h3>
              </div>
            <% end %>
            </div>
        <% end %>
      </div>
    </div>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/flats/show.html.erb
<div class="main-container" data-controller="display-booking">
  <div class= "container-flat-show">
    <div class="card-flat">
      <div class="img-card-elf">
        <%= cl_image_tag @flat.photo.key, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="card-flat-infos">
        <div class="card-flat-infos-title">
          <h2><%= @flat.name %></h2>
        </div>
        <div class="card-elves-infos-content">
          <p><i class="fas fa-info-circle"></i> <%= @flat.description %></p>
          <p><i class="fas fa-info-circle"></i> <%= @flat.town %></p>
          <p><i class="fas fa-euro-sign"></i> <%= @flat.price_per_day %>€ / jour</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container-form-booking <%= 'inactive' unless @booking.errors.any? %>" data-display-booking-target="form">
  <% if user_signed_in? %>

    <div class="form-booking">
      <%= simple_form_for [@flat, @booking], data: { controller: "total-price", total_price_per_day_value: @flat.price_per_day } do |f| %>
        <%= f.input :start_date, html5: true, input_html: { data: { total_price_target: "startdate", action: "total-price#computePrice" } }%>
        <%= f.input :end_date, html5: true, input_html: { data: { total_price_target: "enddate", action: "total-price#computePrice" } }%>
        <div class= container_total_price>
          <div class="d-flex">
            <%= f.button :submit, value: "Book", class: "btn btn btn-primary text-white px-3 py-2  fs-10 mt-3 mx-1"%>
            <%= link_to "List of flats", flats_path, class: "btn btn-info px-3 py-2  fs-10 mt-3" %>
          </div>
          <div data-total-price-target="totalPriceDiv" class= price></div>
        </div>
      <% end %>
    </div>

    <% else %>
      <div class="col pt-1" data-controller="popup">
        <div class="d-flex">
          <button class="btn btn-primary btn-lg" data-action="click->popup#panel" data-popup-target="button"> Book now! </button>
          <%= link_to "Retour à la liste", flats_path, class: "btn btn-info" %>
        </div>

        <div href="#" class="yeahh d-none" data-popup-target="link">
          <h2>Oups... You should be connected to book this fabulous flat</h2>
          <div>
            <a class="button-login" href="http://localhost:3000/users/sign_in">Log in now</a>
            <button class="btn btn-primary" data-action="click->popup#reset"> Ok </button>
          </div>
        </div>
        <div class="opaq opacity-50 d-none" data-popup-target="panel">
        </div>
      </div>
    <%end%>
  </div>
</div>


<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samyrbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"/>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar"  unless current_page?('/') %>
  <%= render "shared/flashes" %>
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "home-banner">

  <%= link_to "Explore flats !", flats_path, class: "home-button" %>

</div>

<div class = "card-home">
  <div class = "container-home">

    <div class = "card-home-column">
      <div class = "image-card-home1">
      </div>
      <div class = "text-card-home-top">
        <h3>Discover other horizons</h3>
        <p>Stay in a new space with absolute comfort</p>
      </div>
    </div>

     <div class = "card-home-column">
      <div class = "image-card-home2">
      </div>
      <div class = "text-card-home-top">
        <h3>Travel easily</h3>
        <p>In just a few clicks you accommodate yourself</p>
      </div>
    </div>

     <div class = "card-home-column">
      <div class = "image-card-home3">
      </div>
      <div class = "text-card-home-top">
        <div>
          <h3>Stay safe</h3>
          <p>Stay in a new space with safety and measures</p>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/profiles/show.html.erb
<div class="swiper mySwiper container">
  <div class="swiper-wrapper content">
  <% @flats.each do |flat|%>
    <div class=" swiper-slide card-profile">
      <div class="card-content">

        <div class="image">
          <%= cl_image_tag( flat.photo.key, :size => "150x150", :crop => "fill", :style =>  "border-radius: 50%; border: 3px solid white") %>
        </div>

        <div class="description">
          <span class="name"><%= flat.name %></span>
          <span class="town"><%= flat.town %></span>
          <span class="price-a-day"> price a day : <%= flat.price_per_day %></span>
        </div>

        <div class="rating">
          <i class="fa-solid fa-star"></i>
          <i class="fa-solid fa-star"></i>
          <i class="fa-solid fa-star"></i>
          <i class="fa-solid fa-star"></i>
          <i class="fa-solid fa-star"></i>
        </div>

      </div>
    </div>
    <% end %>
  </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-pagination"></div>

 <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

    <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        slidesPerGroup: 3,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
        },
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
      });
    </script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer" style="background-color:#f1f1f1">
  <div class="footer-links">
    <a href="https://github.com/pc56"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/dragon.official/"><i class="fab fa-instagram"></i></a>
    <a href="https://fr-fr.facebook.com/AGHSCDragonHelico/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/DragonsOfficiel"><i class="fab fa-twitter"></i></a>
    <a href="https://fr.linkedin.com/company/groupe-dragon"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Ce site vous est proposé avec <i class="fas fa-heart"></i> par Céline, Denis, Pierre et Samy
  </div>
</div> %>


<footer class = "footer-container">

  <div class = "footer-content">
    <div class = "footer-icons">
    <p>Made by Samy</p>
    <a href="https://www.linkedin.com/feed/"><i class="fa-brands fa-linkedin"></i></a>
    <a href="https://slack.com/intl/fr-fr/"><i class="fa-brands fa-slack"></i></a>
    <a href="https://www.facebook.com/"><i class="fa-brands fa-square-facebook"></i></a>
    <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram"></i></a>
    </div>
    <div class = "footer-names">
     <p>FAQS</p>
     <p>TERMS AND CONDITIONS</p>
     <p>SPONSORS</p>
     <p>PAYMENT INFO</p>
     <p>CONTACT US</p>
    </div>
  </div>

</footer>

app/views/shared/_navbar.html.erb
<div class = "navbar">

  <div class= "navbar-logo">
  </div>

  <div class="navbar-content">

    <%= link_to "/flats" do %>
      <div class = "flat-navbar"><p>Flats</p></div>
    <% end %>

    <% unless user_signed_in?%>
      <%= link_to "/users/sign_in" do %>
      <div class= "sign-navbar"><p>Sign in</p></div>
      <% end %>
    <% end %>




  </div>

  <div class="navbar-avatar">
  </div>

</div>